name: Pull Requests Auto-Merge
on:
  pull_request:

jobs:
  auto-merge:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    permissions:
      contents: write
      pull-requests: write
    uses: donniean/hub/.github/workflows/pull-requests.auto-merge.yaml@main
